import type { Mission } from "./types";

const w1: Mission[] = [
  {
    slug: "what-is-live",
    world: "first-contact",
    number: 1,
    title: "What Is Live?",
    tagline: "A DAW with two brains.",
    xp: 50,
    badge: { slug: "first-boot", name: "First Boot" },
    explainer: [
      { kind: "lead", text: "Ableton Live is a Digital Audio Workstation built around two complementary views: Session for non-linear jamming, Arrangement for linear composition." },
      { kind: "para", text: "Where most DAWs only give you a timeline, Live also gives you a grid of clips you can launch in any order. That single idea is why producers, performers, and sound designers all live inside it." },
      { kind: "list", items: [
        "Session View — clip grid, perfect for ideas, loops, live sets.",
        "Arrangement View — timeline, perfect for full songs.",
        "Devices — instruments and effects, all built in.",
        "Browser — your library of sounds, presets and projects.",
      ]},
      { kind: "callout", tone: "key", text: "Almost everything in Live is non-destructive. You can warp, reverse, slice, and the original sample stays intact." },
    ],
    sim: { type: "interface-tour" },
    quiz: [
      { q: "Live's two main views are…", options: ["Mix & Edit", "Session & Arrangement", "Track & Master", "Studio & Live"], answer: 1 },
      { q: "Session View is best for…", options: ["Linear songs", "Mastering", "Non-linear loop launching", "Video scoring"], answer: 2 },
      { q: "Audio editing in Live is…", options: ["Destructive", "Non-destructive", "Read-only", "MIDI-only"], answer: 1 },
    ],
  },
  {
    slug: "interface-tour",
    world: "first-contact",
    number: 2,
    title: "Interface Tour",
    tagline: "Every panel, named.",
    xp: 60,
    badge: { slug: "cartographer", name: "Cartographer" },
    explainer: [
      { kind: "lead", text: "Click the hotspots to learn each region of Live's window." },
      { kind: "list", items: [
        "Control Bar — tempo, transport, metronome, quantization.",
        "Browser — left sidebar with sounds, samples, packs.",
        "Main View — Session grid or Arrangement timeline.",
        "Detail View — clip & device editor, opens at the bottom.",
        "Info View — hover anything, read what it does.",
      ]},
      { kind: "callout", tone: "tip", text: "Tab toggles between Session and Arrangement. Memorize this immediately." },
    ],
    sim: { type: "interface-tour" },
    quiz: [
      { q: "What key toggles Session/Arrangement?", options: ["Spacebar", "Tab", "Enter", "Shift"], answer: 1 },
      { q: "Tempo lives in the…", options: ["Browser", "Detail View", "Control Bar", "Mixer"], answer: 2 },
      { q: "Where do you edit a clip's notes?", options: ["Control Bar", "Browser", "Detail View", "Info View"], answer: 2 },
    ],
  },
  {
    slug: "browser",
    world: "first-contact",
    number: 3,
    title: "The Browser",
    tagline: "Your library, organised.",
    xp: 50,
    explainer: [
      { kind: "lead", text: "The Browser is where you find sounds, samples, presets and projects. Master it and you'll make tracks twice as fast." },
      { kind: "list", items: [
        "Sounds — instrument presets you can drag onto tracks.",
        "Drums — drum kits and one-shots.",
        "Samples — your own audio files.",
        "Packs — Ableton's official sound libraries.",
        "Categories — Live's tagging system (since Live 12).",
      ]},
      { kind: "callout", tone: "key", text: "Live 12 added Sound Similarity Search — pick a sample and Live finds others that sound like it." },
    ],
    sim: { type: "browser-tour" },
    quiz: [
      { q: "Live 12's Similarity Search finds samples by…", options: ["File name", "Sound", "Date", "Size"], answer: 1 },
      { q: "Drag-and-drop from the Browser to…", options: ["A track", "Only Session", "Only Arrangement", "The Control Bar"], answer: 0 },
      { q: "Categories were added in…", options: ["Live 9", "Live 10", "Live 11", "Live 12"], answer: 3 },
    ],
  },
  {
    slug: "preferences",
    world: "first-contact",
    number: 4,
    title: "Preferences",
    tagline: "Set it up once, properly.",
    xp: 40,
    explainer: [
      { kind: "lead", text: "Open Preferences (Cmd/Ctrl + ,) and configure your audio interface, buffer size, MIDI ports, and file locations before you do anything else." },
      { kind: "list", items: [
        "Audio — driver, sample rate, buffer size (lower = less latency, more CPU).",
        "Link/Tempo/MIDI — controllers and Ableton Link.",
        "File/Folder — auto-save, plugin folders, max undo.",
        "Library — where Packs install.",
        "Theme — light, dark, high-contrast.",
      ]},
      { kind: "callout", tone: "warn", text: "Buffer too low → audio glitches. Too high → noticeable input latency. 256 samples is a safe default for most." },
    ],
    sim: { type: "knob-trainer", preset: { mode: "buffer" } },
    quiz: [
      { q: "Lower buffer size means…", options: ["More latency", "Less latency, more CPU", "Less CPU", "Better quality"], answer: 1 },
      { q: "Open Preferences with…", options: ["Cmd/Ctrl + ,", "Cmd/Ctrl + P", "F5", "Tab"], answer: 0 },
      { q: "Where do plugins get scanned?", options: ["Audio tab", "File/Folder + Plug-Ins tab", "Theme tab", "Library tab"], answer: 1 },
    ],
  },
  {
    slug: "files-projects",
    world: "first-contact",
    number: 5,
    title: "Files & Projects",
    tagline: "How Live saves your work.",
    xp: 40,
    explainer: [
      { kind: "lead", text: "A Live Set is a .als file. A Project is the folder around it that holds samples, recordings and presets." },
      { kind: "list", items: [
        "Always 'Collect All and Save' before sharing a project.",
        "Live Pack (.alp) bundles a project for distribution.",
        "Auto-save runs in the background — turn it on.",
        "Export Audio/Video renders your finished track.",
      ]},
      { kind: "callout", tone: "tip", text: "Name tracks and clips as you work. Future-you will thank present-you." },
    ],
    sim: { type: "none" },
    quiz: [
      { q: "A Live Set extension is…", options: [".alp", ".als", ".adv", ".asd"], answer: 1 },
      { q: "To bundle a project for a friend, use…", options: ["Save As", "Collect All and Save", "Export Audio", "Freeze Track"], answer: 1 },
      { q: ".alp files are…", options: ["Live Sets", "Live Packs", "Audio", "Presets"], answer: 1 },
    ],
  },
];

const w2: Mission[] = [
  {
    slug: "session-view",
    world: "two-views",
    number: 6,
    title: "Session View",
    tagline: "The clip grid.",
    xp: 70,
    badge: { slug: "scene-stealer", name: "Scene Stealer" },
    explainer: [
      { kind: "lead", text: "Session View is a grid: tracks (vertical) and scenes (horizontal). Each cell is a clip slot. Launch clips and scenes to build ideas live." },
      { kind: "list", items: [
        "Click a clip to launch it.",
        "Click a Scene Launch button to fire a whole row.",
        "Stop button kills clips on a track.",
        "Quantize controls when clips actually start.",
      ]},
      { kind: "callout", tone: "key", text: "Set Global Quantize to 1 Bar — clips will sync musically no matter when you click." },
    ],
    sim: { type: "session-grid" },
    quiz: [
      { q: "A scene is…", options: ["A column of clips", "A row of clips", "A single clip", "A track"], answer: 1 },
      { q: "Global Quantize 1 Bar means clips start…", options: ["Immediately", "On next bar", "On next beat", "Never"], answer: 1 },
      { q: "Each track plays…", options: ["All clips at once", "One clip at a time", "Two clips", "Whatever you select"], answer: 1 },
    ],
  },
  {
    slug: "arrangement-view",
    world: "two-views",
    number: 7,
    title: "Arrangement View",
    tagline: "The timeline.",
    xp: 70,
    explainer: [
      { kind: "lead", text: "Arrangement is a horizontal timeline. Tracks stack down. Clips are blocks you can move, resize, split and loop." },
      { kind: "list", items: [
        "Press Tab to switch from Session.",
        "Record Arm + Record captures Session performances into Arrangement.",
        "The Loop Brace repeats a section.",
        "Locators bookmark sections (Intro, Verse, Drop).",
      ]},
    ],
    sim: { type: "arrangement" },
    quiz: [
      { q: "Locators are…", options: ["Loop markers", "Section bookmarks", "Automation points", "Clips"], answer: 1 },
      { q: "Recording Session into Arrangement happens when…", options: ["You press Save", "You hit global Record", "You export", "Always automatic"], answer: 1 },
      { q: "Arrangement clips can be…", options: ["Moved & resized", "Only moved", "Only resized", "Neither"], answer: 0 },
    ],
  },
  {
    slug: "clips",
    world: "two-views",
    number: 8,
    title: "Clips 101",
    tagline: "MIDI clips & audio clips.",
    xp: 60,
    explainer: [
      { kind: "lead", text: "A clip is a piece of musical content. MIDI clips contain notes; audio clips contain samples. Both can loop." },
      { kind: "list", items: [
        "Clip View shows clip properties: pitch, gain, loop, warp.",
        "Notes panel for MIDI editing.",
        "Sample panel for audio editing & warping.",
        "Envelopes panel for automation inside the clip.",
      ]},
    ],
    sim: { type: "piano-roll" },
    quiz: [
      { q: "MIDI clips contain…", options: ["Audio", "Notes", "Both", "Plugins"], answer: 1 },
      { q: "Clip-level automation lives in…", options: ["Notes", "Envelopes", "Sample", "Mixer"], answer: 1 },
      { q: "Audio warping is set in the…", options: ["Notes panel", "Sample panel", "Mixer", "Browser"], answer: 1 },
    ],
  },
  {
    slug: "tracks",
    world: "two-views",
    number: 9,
    title: "Tracks",
    tagline: "Audio. MIDI. Return. Group. Master.",
    xp: 50,
    explainer: [
      { kind: "list", items: [
        "Audio Track — records & plays audio.",
        "MIDI Track — holds MIDI clips, hosts an instrument.",
        "Return Track — destination for sends (reverb, delay).",
        "Group Track — folder for routing many tracks together.",
        "Master Track — the final output.",
      ]},
    ],
    sim: { type: "mixer" },
    quiz: [
      { q: "Reverb sends go to a…", options: ["Group", "Return", "Master", "MIDI"], answer: 1 },
      { q: "An instrument lives on a…", options: ["Audio", "MIDI", "Return", "Master"], answer: 1 },
      { q: "Group tracks are like…", options: ["Folders", "Plugins", "Sends", "Clips"], answer: 0 },
    ],
  },
  {
    slug: "scenes-follow",
    world: "two-views",
    number: 10,
    title: "Scenes & Follow Actions",
    tagline: "Make clips play themselves.",
    xp: 70,
    badge: { slug: "auto-pilot", name: "Auto Pilot" },
    explainer: [
      { kind: "lead", text: "A scene fires a whole row. Follow Actions tell each clip what to do when it ends — jump to next, loop, play random." },
      { kind: "list", items: [
        "Set scene tempo & time signature for live sets.",
        "Follow Actions: Stop, Play Again, Previous, Next, First, Last, Any, Other.",
        "Live 11+ added linked Follow Action chances per row.",
      ]},
    ],
    sim: { type: "session-grid", preset: { followActions: true } },
    quiz: [
      { q: "Follow Actions trigger…", options: ["When a clip ends", "When you click", "On bar 1", "On record"], answer: 0 },
      { q: "Scenes can override…", options: ["Tempo", "Sample rate", "Buffer", "Theme"], answer: 0 },
      { q: "Which is NOT a Follow Action?", options: ["Next", "Other", "Reverse", "Stop"], answer: 2 },
    ],
  },
];

const w3: Mission[] = [
  {
    slug: "midi-piano-roll",
    world: "midi-audio",
    number: 11,
    title: "MIDI Piano Roll",
    tagline: "Click. Drag. Compose.",
    xp: 80,
    badge: { slug: "note-ninja", name: "Note Ninja" },
    explainer: [
      { kind: "lead", text: "Double-click a MIDI clip to open the piano roll. Pencil mode draws notes; default mode selects them." },
      { kind: "list", items: [
        "B toggles Pencil Mode.",
        "Velocity = how hard a note is hit.",
        "Quantize aligns notes to the grid.",
        "Live 12 added Generative MIDI tools: Stacks, Rhythm, Shape, Seed.",
      ]},
      { kind: "callout", tone: "key", text: "Hold Shift to constrain note movement. Hold Cmd/Ctrl while drawing for finer pitch increments." },
    ],
    sim: { type: "piano-roll" },
    quiz: [
      { q: "B toggles…", options: ["Browser", "Pencil mode", "Bar count", "Bypass"], answer: 1 },
      { q: "Velocity controls…", options: ["Pitch", "Length", "How hard", "Quantize"], answer: 2 },
      { q: "Live 12 generative MIDI is in…", options: ["Mixer", "Browser", "Note transformations", "Master"], answer: 2 },
    ],
  },
  {
    slug: "audio-clips",
    world: "midi-audio",
    number: 12,
    title: "Audio Clips",
    tagline: "Samples that bend to your will.",
    xp: 60,
    explainer: [
      { kind: "lead", text: "Audio clips reference a sample file. They can be transposed, reversed, looped, sliced, and warped — all without touching the original." },
      { kind: "list", items: [
        "Transpose pitch in semitones (-48 to +48).",
        "Detune in cents.",
        "Reverse, Crop, Consolidate.",
        "Set warp markers to align beats.",
      ]},
    ],
    sim: { type: "warp-lab" },
    quiz: [
      { q: "Editing an audio clip is…", options: ["Destructive", "Non-destructive", "Disabled", "MIDI-only"], answer: 1 },
      { q: "Transpose unit is…", options: ["Hz", "Cents", "Semitones", "Bars"], answer: 2 },
      { q: "Detune unit is…", options: ["Hz", "Cents", "Semitones", "Bars"], answer: 1 },
    ],
  },
  {
    slug: "warping",
    world: "midi-audio",
    number: 13,
    title: "Warping",
    tagline: "Lock any sample to your tempo.",
    xp: 90,
    badge: { slug: "warp-wizard", name: "Warp Wizard" },
    explainer: [
      { kind: "lead", text: "Warping stretches audio in time without changing its pitch. Place warp markers on transients, set a Warp Mode, and the clip follows your project tempo." },
      { kind: "list", items: [
        "Beats — drums and percussive material.",
        "Tones — melodic mono material.",
        "Texture — pads, ambience.",
        "Re-Pitch — old-school speed up/down (pitch follows).",
        "Complex / Complex Pro — full mixes (CPU heavy).",
      ]},
      { kind: "callout", tone: "tip", text: "Drag a transient to set a warp marker. Right-click → Warp From Here (Straight) for a quick lock to grid." },
    ],
    sim: { type: "warp-lab" },
    quiz: [
      { q: "Best mode for full mixes?", options: ["Beats", "Tones", "Re-Pitch", "Complex Pro"], answer: 3 },
      { q: "Warping changes…", options: ["Pitch only", "Time without pitch", "Both equally", "Volume"], answer: 1 },
      { q: "Re-Pitch behaves like…", options: ["A vocoder", "A tape machine", "A reverb", "A limiter"], answer: 1 },
    ],
  },
  {
    slug: "recording-audio",
    world: "midi-audio",
    number: 14,
    title: "Recording Audio",
    tagline: "Get sound in.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Set the track input (Ext. In 1, etc.).",
        "Arm the track (red circle).",
        "Hit Record. Live records into the focused view.",
        "Monitor: In, Auto, Off.",
      ]},
      { kind: "callout", tone: "warn", text: "Always check input level — peak around -12 to -6 dB, never clip into the red." },
    ],
    sim: { type: "mixer", preset: { record: true } },
    quiz: [
      { q: "Arm a track to…", options: ["Solo it", "Record it", "Mute it", "Group it"], answer: 1 },
      { q: "Monitor 'Auto' means…", options: ["Always on", "Always off", "On while armed & not playing back", "Off while armed"], answer: 2 },
      { q: "Healthy input level is around…", options: ["0 dB", "-12 to -6 dB", "+6 dB", "-40 dB"], answer: 1 },
    ],
  },
  {
    slug: "comping",
    world: "midi-audio",
    number: 15,
    title: "Comping",
    tagline: "Stitch the perfect take.",
    xp: 70,
    explainer: [
      { kind: "lead", text: "Take Lanes (Live 11+) let you record multiple passes onto a track and assemble the best moments into one comp." },
      { kind: "list", items: [
        "Right-click a track header → Show Take Lanes.",
        "Each loop pass becomes a new lane.",
        "Click any segment to promote it to the master comp.",
        "Works for both audio and MIDI.",
      ]},
    ],
    sim: { type: "arrangement", preset: { takes: true } },
    quiz: [
      { q: "Take Lanes were added in…", options: ["Live 9", "Live 10", "Live 11", "Live 12"], answer: 2 },
      { q: "Comping works on…", options: ["Audio only", "MIDI only", "Both", "Returns"], answer: 2 },
      { q: "Each loop pass becomes…", options: ["A scene", "A take lane", "A device", "A locator"], answer: 1 },
    ],
  },
  {
    slug: "slicing",
    world: "midi-audio",
    number: 16,
    title: "Slicing to MIDI",
    tagline: "Turn any loop into a playable kit.",
    xp: 70,
    explainer: [
      { kind: "lead", text: "Right-click any audio clip → Slice to New MIDI Track. Live chops it on transients (or grid) and loads each slice into a Drum Rack pad." },
      { kind: "list", items: [
        "Slice by warp markers, beats, or transients.",
        "Each slice maps to a MIDI note.",
        "Re-trigger, re-order, glitch — instant remix.",
      ]},
    ],
    sim: { type: "drum-pad", preset: { sliced: true } },
    quiz: [
      { q: "Slicing produces a…", options: ["Sampler", "Drum Rack", "Wavetable", "Operator"], answer: 1 },
      { q: "You can slice by…", options: ["Transients only", "Beats only", "Transients, beats, or warp markers", "Bars only"], answer: 2 },
      { q: "Each slice is triggered by…", options: ["A scene", "A MIDI note", "A macro", "A send"], answer: 1 },
    ],
  },
];

const w4: Mission[] = [
  {
    slug: "instruments-overview",
    world: "devices",
    number: 17,
    title: "Instruments Overview",
    tagline: "Your built-in synths.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Operator — FM synth, deep & metallic.",
        "Wavetable — modern wavetable, the workhorse.",
        "Drift — analog-style mono/poly synth (Live 11+).",
        "Sampler / Simpler — play your own audio as instruments.",
        "Drum Rack — kit container.",
        "Meld (Live 12) — MPE-first dual-engine synth.",
      ]},
    ],
    sim: { type: "knob-trainer", preset: { synth: "wavetable" } },
    quiz: [
      { q: "Meld is what kind of synth?", options: ["FM", "Subtractive", "MPE dual-engine", "Granular"], answer: 2 },
      { q: "Operator uses…", options: ["Subtractive", "FM", "Wavetable", "Granular"], answer: 1 },
      { q: "Drift was added in…", options: ["Live 9", "Live 10", "Live 11", "Live 12"], answer: 2 },
    ],
  },
  {
    slug: "drum-rack",
    world: "devices",
    number: 18,
    title: "Drum Rack",
    tagline: "16 pads, infinite kits.",
    xp: 70,
    badge: { slug: "kit-builder", name: "Kit Builder" },
    explainer: [
      { kind: "lead", text: "Drum Rack is a container — each pad hosts a Simpler (or any device chain) on its own MIDI note." },
      { kind: "list", items: [
        "Drag samples onto pads.",
        "Each pad has its own chain, mixer, sends.",
        "Choke groups silence other pads (hi-hats).",
        "Right-click pad → Browse for replacements.",
      ]},
    ],
    sim: { type: "drum-pad" },
    quiz: [
      { q: "Choke groups are useful for…", options: ["Reverb", "Hi-hats", "Bass", "Master"], answer: 1 },
      { q: "Each pad hosts…", options: ["A track", "A chain (often a Simpler)", "A scene", "A clip"], answer: 1 },
      { q: "Drum Rack pads map to…", options: ["Audio inputs", "MIDI notes", "Sends", "Macros"], answer: 1 },
    ],
  },
  {
    slug: "wavetable",
    world: "devices",
    number: 19,
    title: "Wavetable",
    tagline: "Modern synthesis, made friendly.",
    xp: 70,
    explainer: [
      { kind: "list", items: [
        "Two oscillators scan through wavetables.",
        "Sub osc, noise, two filters, two envelopes, two LFOs.",
        "Modulation matrix at the bottom — drag any source to any destination.",
        "Unison modes for huge stacks.",
      ]},
    ],
    sim: { type: "knob-trainer", preset: { synth: "wavetable" } },
    quiz: [
      { q: "Wavetable's mod matrix is at the…", options: ["Top", "Bottom", "Side", "Hidden"], answer: 1 },
      { q: "Wavetable has how many oscillators?", options: ["1", "2", "4", "6"], answer: 1 },
      { q: "Unison creates…", options: ["Single voice", "Layered detuned voices", "Reverb", "Distortion"], answer: 1 },
    ],
  },
  {
    slug: "operator",
    world: "devices",
    number: 20,
    title: "Operator",
    tagline: "FM synthesis demystified.",
    xp: 80,
    explainer: [
      { kind: "lead", text: "Operator is a 4-operator FM synth. One operator modulates another's frequency to create rich harmonics." },
      { kind: "list", items: [
        "Pick an algorithm to set how operators connect.",
        "Carriers make sound; modulators shape it.",
        "Higher modulator level = more harmonics.",
        "Coarse/Fine ratio defines the timbre.",
      ]},
    ],
    sim: { type: "knob-trainer", preset: { synth: "operator" } },
    quiz: [
      { q: "Operator has how many operators?", options: ["2", "4", "6", "8"], answer: 1 },
      { q: "Carriers…", options: ["Modulate", "Output sound", "Both", "Neither"], answer: 1 },
      { q: "More modulator level →", options: ["Quieter", "More harmonics", "Less harmonics", "Lower pitch"], answer: 1 },
    ],
  },
  {
    slug: "sampler-simpler",
    world: "devices",
    number: 21,
    title: "Sampler & Simpler",
    tagline: "Play any sound as an instrument.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Simpler — one sample, three modes: Classic, One-Shot, Slice.",
        "Sampler — full multi-sample instrument with zones, key/velocity mapping.",
        "Drag any audio onto a MIDI track to auto-create a Simpler.",
      ]},
    ],
    sim: { type: "drum-pad", preset: { simpler: true } },
    quiz: [
      { q: "Simpler's three modes are…", options: ["Loop, Pad, Drum", "Classic, One-Shot, Slice", "FM, AM, PM", "A, B, C"], answer: 1 },
      { q: "For multi-sampled instruments use…", options: ["Simpler", "Sampler", "Operator", "Drift"], answer: 1 },
      { q: "Drag audio to a MIDI track →", options: ["Sampler", "Simpler", "Operator", "Drum Rack"], answer: 1 },
    ],
  },
  {
    slug: "eq-eight",
    world: "devices",
    number: 22,
    title: "EQ Eight",
    tagline: "Shape every frequency.",
    xp: 70,
    badge: { slug: "frequency-fox", name: "Frequency Fox" },
    explainer: [
      { kind: "lead", text: "EQ Eight gives you 8 bands of parametric EQ, each with multiple filter shapes." },
      { kind: "list", items: [
        "High-pass to remove sub rumble.",
        "Bell to boost or cut a focused band.",
        "Shelves for broad tilts.",
        "Hold Cmd/Ctrl + drag for fine adjustments.",
      ]},
      { kind: "callout", tone: "key", text: "Subtractive EQ before additive: cut what's wrong before boosting what's right." },
    ],
    sim: { type: "ear-training", preset: { mode: "eq" } },
    quiz: [
      { q: "EQ Eight has how many bands?", options: ["4", "6", "8", "10"], answer: 2 },
      { q: "Remove sub rumble with a…", options: ["High shelf", "Low shelf", "High-pass", "Notch"], answer: 2 },
      { q: "Subtractive EQ means…", options: ["Boost first", "Cut first", "Only boost", "Only shelf"], answer: 1 },
    ],
  },
  {
    slug: "compressor",
    world: "devices",
    number: 23,
    title: "Compressor",
    tagline: "Tame dynamics. Add punch.",
    xp: 80,
    badge: { slug: "dyna-master", name: "Dyna Master" },
    explainer: [
      { kind: "list", items: [
        "Threshold — level above which compression kicks in.",
        "Ratio — how much it squashes.",
        "Attack — how fast it clamps.",
        "Release — how fast it lets go.",
        "Knee — soft vs hard transition.",
        "Makeup — bring level back up.",
      ]},
      { kind: "callout", tone: "tip", text: "Slower attack = more transient through. Faster attack = more squash." },
    ],
    sim: { type: "ear-training", preset: { mode: "comp" } },
    quiz: [
      { q: "Slower attack lets through more…", options: ["Bass", "Transients", "Reverb", "Pitch"], answer: 1 },
      { q: "Ratio of 4:1 means…", options: ["4 dB in = 1 dB over", "1 dB in = 4 dB over", "No effect", "Limiter"], answer: 0 },
      { q: "Makeup gain compensates for…", options: ["Pitch", "Lost level", "Latency", "Width"], answer: 1 },
    ],
  },
  {
    slug: "reverb-delay",
    world: "devices",
    number: 24,
    title: "Reverb & Delay",
    tagline: "Space and echo.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Reverb — space simulation; size, decay, dry/wet.",
        "Hybrid Reverb (Live 11+) blends convolution with algorithmic.",
        "Delay — echoes synced to tempo.",
        "Echo — analog-flavored delay with character.",
        "Always put reverb/delay on a Return for sharing across tracks.",
      ]},
    ],
    sim: { type: "ear-training", preset: { mode: "reverb" } },
    quiz: [
      { q: "Hybrid Reverb arrived in…", options: ["Live 9", "Live 10", "Live 11", "Live 12"], answer: 2 },
      { q: "Reverbs are best placed on…", options: ["Each track", "Master", "Returns", "Group"], answer: 2 },
      { q: "Echo is…", options: ["A reverb", "Analog-flavored delay", "A limiter", "A vocoder"], answer: 1 },
    ],
  },
  {
    slug: "saturator-distortion",
    world: "devices",
    number: 25,
    title: "Saturator & Distortion",
    tagline: "Add grit. Add glue.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Saturator — soft to hard saturation curves.",
        "Drive controls how hard you push the curve.",
        "Pedal, Overdrive, Roar (Live 12) — flavored distortions.",
        "Roar adds multi-band processing & feedback paths.",
      ]},
    ],
    sim: { type: "ear-training", preset: { mode: "sat" } },
    quiz: [
      { q: "Roar was added in…", options: ["Live 10", "Live 11", "Live 12", "Live 13"], answer: 2 },
      { q: "Drive in Saturator controls…", options: ["Pitch", "How hard you hit the curve", "Reverb size", "Pan"], answer: 1 },
      { q: "Roar is a…", options: ["Reverb", "Multi-band distortion", "Compressor", "Synth"], answer: 1 },
    ],
  },
  {
    slug: "midi-effects",
    world: "devices",
    number: 26,
    title: "MIDI Effects",
    tagline: "Process notes before sound.",
    xp: 50,
    explainer: [
      { kind: "list", items: [
        "Arpeggiator — turn chords into runs.",
        "Chord — stack intervals on each note.",
        "Scale — force notes into a scale.",
        "Note Echo — note repeats.",
        "Random / Velocity — humanise or chaos.",
      ]},
    ],
    sim: { type: "piano-roll", preset: { midiFx: true } },
    quiz: [
      { q: "Force notes into a scale with…", options: ["Chord", "Scale", "Random", "Velocity"], answer: 1 },
      { q: "Arpeggiator turns chords into…", options: ["Pads", "Runs", "Reverb", "Bass"], answer: 1 },
      { q: "MIDI effects sit…", options: ["After instrument", "Before instrument", "On Master", "On Return"], answer: 1 },
    ],
  },
  {
    slug: "racks-macros",
    world: "devices",
    number: 27,
    title: "Racks & Macros",
    tagline: "Wrap chains. Map controls.",
    xp: 80,
    badge: { slug: "macro-maxxer", name: "Macro Maxxer" },
    explainer: [
      { kind: "lead", text: "Racks group devices into a single unit. Macros are 16 knobs you map to any parameter inside the rack." },
      { kind: "list", items: [
        "Instrument Rack, Audio Effect Rack, MIDI Effect Rack, Drum Rack.",
        "Chain Selector splits zones across chains.",
        "Macro Variations save & recall macro snapshots.",
        "Right-click a parameter → Map to Macro.",
      ]},
    ],
    sim: { type: "knob-trainer", preset: { macros: true } },
    quiz: [
      { q: "How many macros per rack?", options: ["8", "12", "16", "32"], answer: 2 },
      { q: "Macro Variations are…", options: ["Plugins", "Snapshots of macro values", "Sends", "Scenes"], answer: 1 },
      { q: "Chain Selector splits…", options: ["MIDI notes only", "Velocity, key or chain zones", "Audio only", "Returns"], answer: 1 },
    ],
  },
];

const w5: Mission[] = [
  {
    slug: "the-mixer",
    world: "mixing",
    number: 28,
    title: "The Mixer",
    tagline: "Faders, pans, meters.",
    xp: 70,
    explainer: [
      { kind: "list", items: [
        "Volume fader — track level (don't ride hot).",
        "Pan — stereo placement.",
        "Mute / Solo — isolate or silence.",
        "Cue — pre-listen for DJ-style monitoring.",
        "Crossfader A/B — DJ blend across tracks.",
      ]},
    ],
    sim: { type: "mixer" },
    quiz: [
      { q: "Soloing a track…", options: ["Mutes others", "Mutes it", "Records it", "Groups it"], answer: 0 },
      { q: "Crossfader is for…", options: ["EQ", "DJ-style A/B blend", "Reverb", "Pitch"], answer: 1 },
      { q: "Cue lets you…", options: ["Pre-listen", "Record", "Solo", "Pan"], answer: 0 },
    ],
  },
  {
    slug: "sends-returns",
    world: "mixing",
    number: 29,
    title: "Sends & Returns",
    tagline: "Share effects. Save CPU.",
    xp: 70,
    badge: { slug: "send-it", name: "Send It" },
    explainer: [
      { kind: "lead", text: "Instead of a reverb on every track, put one on a Return and send each track to it. Cleaner, lighter, more cohesive." },
      { kind: "list", items: [
        "Cmd/Ctrl + Alt + T — create Return Track.",
        "Each track gets a Send knob per Return.",
        "Pre/Post toggle: Pre = send before fader, Post = after.",
      ]},
    ],
    sim: { type: "routing-puzzle" },
    quiz: [
      { q: "Pre-fader send is independent of…", options: ["Pan", "Volume fader", "Solo", "Mute"], answer: 1 },
      { q: "Returns receive…", options: ["MIDI", "Sends", "Inputs", "Scenes"], answer: 1 },
      { q: "Why use a return reverb?", options: ["Louder", "CPU & cohesion", "Pitch shift", "Quantize"], answer: 1 },
    ],
  },
  {
    slug: "groups-routing",
    world: "mixing",
    number: 30,
    title: "Groups & Routing",
    tagline: "Sub-mixes and signal flow.",
    xp: 80,
    explainer: [
      { kind: "list", items: [
        "Cmd/Ctrl + G groups tracks.",
        "Group is a real audio bus — process it.",
        "Track In/Out lets you route any track anywhere.",
        "Audio From: external input, another track, Resampling.",
      ]},
    ],
    sim: { type: "routing-puzzle", preset: { groups: true } },
    quiz: [
      { q: "Group tracks are…", options: ["Folders only", "Real audio buses", "Returns", "MIDI"], answer: 1 },
      { q: "Resampling sends Master back to…", options: ["A scene", "An audio track input", "A return", "A clip"], answer: 1 },
      { q: "Cmd/Ctrl + G…", options: ["Saves", "Groups", "Quantizes", "Records"], answer: 1 },
    ],
  },
  {
    slug: "automation",
    world: "mixing",
    number: 31,
    title: "Automation",
    tagline: "Make parameters move.",
    xp: 80,
    badge: { slug: "auto-mate", name: "Auto Mate" },
    explainer: [
      { kind: "lead", text: "Automation records parameter changes over time. Press A in Arrangement to show automation lanes; draw or record." },
      { kind: "list", items: [
        "Click any parameter then choose it from the lane menu.",
        "Curves: linear, then drag a midpoint to bend.",
        "Live 11+ added shaped automation curves.",
        "Clip Envelopes hold automation inside a single clip.",
      ]},
    ],
    sim: { type: "arrangement", preset: { automation: true } },
    quiz: [
      { q: "Show automation in Arrangement with…", options: ["B", "A", "S", "M"], answer: 1 },
      { q: "Clip-only automation lives in…", options: ["Mixer", "Clip Envelopes", "Master", "Returns"], answer: 1 },
      { q: "Curved automation arrived in…", options: ["Live 9", "Live 10", "Live 11", "Live 12"], answer: 2 },
    ],
  },
  {
    slug: "modulation-lanes",
    world: "mixing",
    number: 32,
    title: "Modulation Lanes",
    tagline: "Beyond automation.",
    xp: 70,
    explainer: [
      { kind: "lead", text: "Modulation in Live 12 is offset-based — it nudges a parameter relative to its current value, on top of automation." },
      { kind: "list", items: [
        "Arrangement Modulation lanes (Live 12).",
        "Combine with macros and LFOs (Max for Live).",
        "Great for evolving textures.",
      ]},
    ],
    sim: { type: "arrangement", preset: { modulation: true } },
    quiz: [
      { q: "Modulation in Live 12 is…", options: ["Absolute", "Offset-based", "MIDI-only", "Disabled"], answer: 1 },
      { q: "Modulation stacks with…", options: ["Nothing", "Automation", "Sends only", "Solo"], answer: 1 },
      { q: "Modulation lanes appeared in…", options: ["Live 10", "Live 11", "Live 12", "Live 8"], answer: 2 },
    ],
  },
  {
    slug: "sidechain",
    world: "mixing",
    number: 33,
    title: "Sidechain Compression",
    tagline: "The pump.",
    xp: 90,
    badge: { slug: "sidechain-sniper", name: "Sidechain Sniper" },
    explainer: [
      { kind: "lead", text: "Use the kick to duck the bass (or pads). Open the Compressor's Sidechain panel and set the kick track as input." },
      { kind: "list", items: [
        "Threshold sets when the duck starts.",
        "Ratio sets how deep.",
        "Attack & release sculpt the pump shape.",
        "Try fast attack, medium release for classic dance pump.",
      ]},
    ],
    sim: { type: "ear-training", preset: { mode: "sidechain" } },
    quiz: [
      { q: "Sidechain ducks…", options: ["The kick", "The track being compressed", "The reverb", "Master"], answer: 1 },
      { q: "Classic pump uses…", options: ["Slow attack, slow release", "Fast attack, medium release", "No release", "Soft knee only"], answer: 1 },
      { q: "Sidechain input panel is on the…", options: ["EQ", "Compressor", "Reverb", "Saturator"], answer: 1 },
    ],
  },
  {
    slug: "max-for-live",
    world: "mixing",
    number: 34,
    title: "Max for Live",
    tagline: "Build your own devices.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Max for Live (M4L) is a visual coding env baked into Live Suite.",
        "Hundreds of free devices on maxforlive.com.",
        "Build custom synths, sequencers, MIDI tools.",
        "Convolution Reverb, LFO, Envelope Follower are official M4L devices.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "M4L ships with…", options: ["Intro", "Standard", "Suite", "Lite"], answer: 2 },
      { q: "Envelope Follower is…", options: ["A clip", "An M4L device", "A scene", "A track"], answer: 1 },
      { q: "Max is…", options: ["Audio editor", "Visual programming env", "Mastering tool", "DJ app"], answer: 1 },
    ],
  },
];

const w6: Mission[] = [
  {
    slug: "push-controllers",
    world: "performance",
    number: 35,
    title: "Push & Controllers",
    tagline: "Get hands on.",
    xp: 60,
    explainer: [
      { kind: "list", items: [
        "Push 3 — hardware instrument, can run Live standalone.",
        "Auto-mapping for popular controllers.",
        "User Remote Scripts for custom mapping.",
      ]},
    ],
    sim: { type: "drum-pad", preset: { push: true } },
    quiz: [
      { q: "Push 3 can run…", options: ["Only with computer", "Standalone", "MIDI only", "Audio only"], answer: 1 },
      { q: "Custom mapping uses…", options: ["Macros", "Remote Scripts", "Sends", "Cue"], answer: 1 },
      { q: "Push is…", options: ["A plugin", "Hardware", "A scene", "A clip"], answer: 1 },
    ],
  },
  {
    slug: "midi-mapping",
    world: "performance",
    number: 36,
    title: "MIDI Mapping",
    tagline: "Map any knob to anything.",
    xp: 70,
    badge: { slug: "map-master", name: "Map Master" },
    explainer: [
      { kind: "lead", text: "Cmd/Ctrl + M enters MIDI Map mode. Click a parameter, move a control, done. Set min/max ranges per mapping." },
      { kind: "list", items: [
        "Cmd/Ctrl + K — Key Map mode (laptop keys).",
        "Mappings are per Live Set.",
        "Right-click a mapping to invert range.",
      ]},
    ],
    sim: { type: "midi-map" },
    quiz: [
      { q: "MIDI Map mode shortcut…", options: ["Cmd/Ctrl + M", "Cmd/Ctrl + K", "Cmd/Ctrl + L", "Cmd/Ctrl + J"], answer: 0 },
      { q: "Key Map shortcut…", options: ["Cmd/Ctrl + M", "Cmd/Ctrl + K", "Cmd/Ctrl + L", "Cmd/Ctrl + J"], answer: 1 },
      { q: "Mappings save…", options: ["Globally", "Per Live Set", "Per Pack", "Per scene"], answer: 1 },
    ],
  },
  {
    slug: "tempo-following",
    world: "performance",
    number: 37,
    title: "Tempo Following",
    tagline: "Live follows you.",
    xp: 60,
    explainer: [
      { kind: "lead", text: "Tempo Follower (Live 11+) listens to an audio input (e.g. drummer) and tracks tempo in real time." },
      { kind: "list", items: [
        "Set Audio From in the Tempo Follower preferences.",
        "Engage the Follow button on the tempo display.",
        "Best with strong rhythmic input.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "Tempo Follower added in…", options: ["Live 9", "Live 10", "Live 11", "Live 12"], answer: 2 },
      { q: "It follows…", options: ["MIDI clock", "Audio input", "Scene tempo", "Cue"], answer: 1 },
      { q: "Best input is…", options: ["Pad", "Strong rhythmic source", "Reverb", "Silence"], answer: 1 },
    ],
  },
  {
    slug: "cv-tools",
    world: "performance",
    number: 38,
    title: "CV Tools",
    tagline: "Talk to modular.",
    xp: 50,
    explainer: [
      { kind: "list", items: [
        "CV Instrument & CV Triggers send pitch/gate to Eurorack via DC-coupled interface.",
        "CV In analyses incoming CV.",
        "Use to sequence hardware from MIDI clips.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "CV needs a … interface", options: ["AC-coupled", "DC-coupled", "USB-only", "MIDI-only"], answer: 1 },
      { q: "CV Tools talk to…", options: ["Plugins", "Modular synths", "Push", "Returns"], answer: 1 },
      { q: "CV In…", options: ["Sends CV", "Receives CV", "Sends MIDI", "Records audio"], answer: 1 },
    ],
  },
  {
    slug: "ableton-link",
    world: "performance",
    number: 39,
    title: "Ableton Link",
    tagline: "Sync apps over Wi-Fi.",
    xp: 50,
    explainer: [
      { kind: "lead", text: "Link keeps multiple devices on the same beat over a local network — no cables, no master clock." },
      { kind: "list", items: [
        "Toggle in the Control Bar.",
        "Works with hundreds of apps and hardware.",
        "Each peer can change tempo; everyone follows.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "Link sync uses…", options: ["MIDI cable", "Wi-Fi/LAN", "Audio cable", "USB only"], answer: 1 },
      { q: "Link tempo control is…", options: ["Single master", "Anyone can change", "Locked", "Read-only"], answer: 1 },
      { q: "Link is…", options: ["Paid plugin", "Free, built-in", "Hardware only", "iOS only"], answer: 1 },
    ],
  },
  {
    slug: "exporting",
    world: "performance",
    number: 40,
    title: "Exporting",
    tagline: "Render the final file.",
    xp: 60,
    badge: { slug: "shipped-it", name: "Shipped It" },
    explainer: [
      { kind: "lead", text: "Cmd/Ctrl + Shift + R opens Export Audio/Video. Set the loop brace to define the region first." },
      { kind: "list", items: [
        "Render as Loop renders just the loop.",
        "WAV 24-bit / 44.1 kHz for distribution; 32-bit float for mastering hand-off.",
        "Normalize off — leave headroom.",
        "Render Each Track separately for stems.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "For mastering hand-off use…", options: ["MP3", "WAV 16-bit", "WAV 24-bit / 32-bit float", "FLAC"], answer: 2 },
      { q: "Stems come from…", options: ["Render Master", "Render Each Track", "Render Loop", "Render MIDI"], answer: 1 },
      { q: "Export shortcut…", options: ["Cmd/Ctrl + R", "Cmd/Ctrl + Shift + R", "Cmd/Ctrl + E", "F12"], answer: 1 },
    ],
  },
  {
    slug: "live-sets-projects",
    world: "performance",
    number: 41,
    title: "Live Sets & Projects",
    tagline: "Stay organised.",
    xp: 40,
    explainer: [
      { kind: "list", items: [
        "Project = folder, Set = .als file inside it.",
        "Templates save your default Set.",
        "Bounce in Place freezes a track to audio.",
        "Freeze + Flatten trades CPU for disk.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "Freezing trades…", options: ["RAM for CPU", "CPU for disk", "Disk for RAM", "Quality for size"], answer: 1 },
      { q: "Bounce in Place…", options: ["Renders to audio in place", "Deletes a track", "Exports stems", "Locks tempo"], answer: 0 },
      { q: "Templates set your…", options: ["Default Live Set", "Tempo only", "Theme", "Plugin folder"], answer: 0 },
    ],
  },
  {
    slug: "troubleshooting",
    world: "performance",
    number: 42,
    title: "Troubleshooting",
    tagline: "When things break.",
    xp: 50,
    explainer: [
      { kind: "list", items: [
        "Crackling? Raise buffer size, freeze tracks.",
        "Plugins not showing? Re-scan in Preferences.",
        "Latency issues? Check Driver Error Compensation.",
        "Lost project? Check Auto-Save folder.",
      ]},
    ],
    sim: { type: "none" },
    quiz: [
      { q: "Crackling fix #1…", options: ["Lower buffer", "Raise buffer / freeze", "Add reverb", "Solo"], answer: 1 },
      { q: "Auto-saves are in the…", options: ["Trash", "Project's Backup folder", "Library root", "Master track"], answer: 1 },
      { q: "Plugins missing →", options: ["Re-scan in Preferences", "Reinstall Live", "New project", "Disable MIDI"], answer: 0 },
    ],
  },
];

export const MISSIONS: Mission[] = [...w1, ...w2, ...w3, ...w4, ...w5, ...w6];

export const missionsByWorld = (world: string) =>
  MISSIONS.filter((m) => m.world === world).sort((a, b) => a.number - b.number);

export const missionBySlug = (slug: string) => MISSIONS.find((m) => m.slug === slug);

export const nextMission = (slug: string) => {
  const i = MISSIONS.findIndex((m) => m.slug === slug);
  return i >= 0 && i < MISSIONS.length - 1 ? MISSIONS[i + 1] : null;
};
